const funnyTitles = [
     "Maestro/a del Rumor",
     "Chismosito Pro",
     "Detective Picante",
     "Espía Secreto/a",
     "Infiltrado/a VIP",
     "Recolector/a de Secretos",
     "Chisme Master",
     "Lengua Suelta",
     "Bocata Picante",
     "Agente Secreto/a",
     "Chismógrafo Elite",
     "Bocina Premium",
     "Susurrador/a Pro",
     "Soplo/a Intenso",
     "Cotilla Supreme",
     "Radar del Chisme",
     "Experto/a en Rumores",
     "Secretero/a Pro",
     "Chisme Hunter",
     "Cotilla Master",
     "Detective Privado/a",
     "Bocina Traviesa",
     "Informante Elite",
     "Cazador/a de Secretos",
     "Lengua Ardiente",
     "Oídos Indiscretos",
     "Chisme Champion",
     "Soplo/a Ardiente",
     "Radar Picantón",
     "Bocina Intensa",
     "Espía Travieso/a",
     "Chisme Legendario",
     "Cotilla Supremo/a",
     "Susurrador/a Elite",
     "Detective Hot",
     "Infiltrado/a Pro",
     "Lengua Peligrosa",
     "Maestro/a Secretero",
     "Chisme Warrior",
     "Cotilla Ardiente",
     "Espía Picante",
     "Radar Indiscreto",
     "Bocina Legendaria",
     "Chismosito Supreme",
     "Detective Travieso",
     "Lengua VIP",
     "Susurrador/a Hot",
     "Cotilla Premium",
     "Chisme Expert",
     "Maestro/a Picante",
];
export const getRandomTitleUser = () => {
     const randomIndex = Math.floor(Math.random() * funnyTitles.length);
     return funnyTitles[randomIndex];
};
